USER_WAITING_TIME = 3
FILEPATH = "filepath"
CAPTION_CONTENT = "caption"
ID_FILENAME = "id_filename"
ID = "id"
    
    
TIKTOK_CREATOR_CENTER = "https://www.tiktok.com/creator-center/upload?from=upload"
LOGO ='//*[@id="root"]/div[1]/a/div/svg'
    
UPLOAD_CONTAINER = '//*[@id="root"]/div/div/div/div/div/div/div/div'

UPLOAD_CONTAINER_CSS_SELECTOR = "jsx-2751257330 upload-card before-upload-stage"
    
SPLIT_COUNTER_CSS_SELECTOR = "jsx-6342101 split-num-inputr"
    
    
CAPTION_INPUT = '//*[@id="root"]/div/div/div/div[2]/div[2]/div[2]/div[1]/div/div[1]/div[2]/div/div/div/div/div/div/div'

POST_BUTTON = "/html/body/div[1]/div/div/div/div[2]/div[2]/div[2]/div[8]/div[2]"

