USER_WAITING_TIME = 3
FILEPATH = "filepath"
CAPTION_CONTENT = "caption"
ID_FILENAME = "id_filename"
    
    
TIKTOK_CREATOR_CENTER = "https://www.tiktok.com/creator-center/upload?from=upload"
    
UPLOAD_CONTAINER = "/html/body/div[1]/div/div/div/div/div/div/div/div"
UPLOAD_CONTAINER_CSS_SELECTOR = "jsx-2751257330 upload-card before-upload-stage"
    
SPLIT_COUNTER_CSS_SELECTOR = "jsx-6342101 split-num-inputr"
    
    
CAPTION_INPUT = "/html/body/div[1]/div/div/div/div[2]/div[2]/div[2]/div[1]/div/div[1]/div[2]/div/div/div/div/div/div/div/div/div/span/span"

POST_BUTTON = "/html/body/div[1]/div/div/div/div[2]/div[2]/div[2]/div[8]/div[2]"